#!/usr/bin/env python3
"""Generate the default pinctrl initcall directly from EDT."""

import argparse
import sys

from device_codegen_common import (
    load_edt,
    node_enabled,
    write_if_changed,
)


PINCTRL_OP_RMW = 0
PINCTRL_OP_WRITE = 1
PINCTRL_OP_CELLS = 4


def parse_args():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument('--edt-pickle', required=True)
    parser.add_argument('--output', required=True)
    return parser.parse_args()


def operation_type_name(operation_type):
    names = {
        PINCTRL_OP_RMW: 'Rmw',
        PINCTRL_OP_WRITE: 'Write',
    }
    if operation_type not in names:
        raise ValueError(
            f'unknown pinctrl operation type: {operation_type}')
    return names[operation_type]


def collect_operations(edt):
    operations = []
    seen = set()

    for node in sorted(
            edt.nodes,
            key=lambda item: (
                item.dep_ordinal is None,
                item.dep_ordinal or 0)):
        if not node_enabled(node):
            continue

        for pinctrl in node.pinctrls:
            if pinctrl.name != 'default':
                continue

            for config_node in pinctrl.conf_nodes:
                pinmux = config_node.props.get('pinmux')
                if pinmux is None:
                    continue
                values = pinmux.val
                if not isinstance(values, list):
                    raise ValueError(
                        f'{config_node.path}: pinmux must be an array')
                if len(values) % PINCTRL_OP_CELLS != 0:
                    raise ValueError(
                        f'{config_node.path}: pinmux length '
                        f'{len(values)} is not a multiple of '
                        f'{PINCTRL_OP_CELLS}')

                for offset in range(
                        0, len(values), PINCTRL_OP_CELLS):
                    operation_type = int(values[offset])
                    operation = {
                        'type': operation_type,
                        'type_name': operation_type_name(
                            operation_type),
                        'address': int(values[offset + 1]),
                        'clear_mask': int(values[offset + 2]),
                        'set_value': int(values[offset + 3]),
                    }
                    key = (
                        operation['type'],
                        operation['address'],
                        operation['clear_mask'],
                        operation['set_value'],
                    )
                    if key in seen:
                        continue
                    seen.add(key)
                    operations.append(operation)

    return operations


def format_u32(value):
    return f'0x{value & 0xFFFFFFFF:X}U'


def render_source(operations):
    lines = [
        '// Auto-generated by gen_pinctrl.py. DO NOT EDIT.',
        '',
    ]
    if not operations:
        lines.extend([
            '// No default pinctrl operations found.',
            '',
        ])
        return '\n'.join(lines)

    lines.extend([
        '#include <init.h>',
        '#include <pinctrl.h>',
        '',
        'namespace hal {',
        '',
        'static const pinctrl::Operation _pinctrl_default[] = {',
    ])
    for operation in operations:
        lines.append(
            f'    {{ pinctrl::OperationType::'
            f'{operation["type_name"]}, '
            f'{format_u32(operation["address"])}, '
            f'{format_u32(operation["clear_mask"])}, '
            f'{format_u32(operation["set_value"])} }},')

    lines.extend([
        '};',
        '',
        'static int _init_pinctrl_default() {',
        '    return static_cast<int>(pinctrl::apply(',
        '        _pinctrl_default,',
        '        sizeof(_pinctrl_default) /',
        '            sizeof(_pinctrl_default[0])));',
        '}',
        '',
        '} // namespace hal',
        '',
        'SYS_INIT(hal::_init_pinctrl_default,',
        '         INITCALL_LEVEL_PRE_KERNEL_1, 5);',
        '',
    ])
    return '\n'.join(lines)


def main():
    args = parse_args()
    try:
        edt = load_edt(args.edt_pickle)
        operations = collect_operations(edt)
        write_if_changed(
            args.output, render_source(operations))
    except (OSError, ValueError) as error:
        print(f'gen_pinctrl.py: error: {error}',
              file=sys.stderr)
        return 1

    print(
        f'Generated {len(operations)} pinctrl operations from EDT')
    return 0


if __name__ == '__main__':
    sys.exit(main())
